name: Grafbase Schema Check
author: Grafbase
description: Run the Grafbase Schema Checks
branding:
  icon: activity
  color: green
inputs:
  grafbase_access_token:
    description: A Grafbase API access token. It can be created from the Grafbase dashboard.
    required: true
  schema:
    description: The schema to check, as GraphQL SDL.
    required: true
  account:
    description: The account of the schema to check against.
    required: true
  project:
    description: The project of the schema to check against.
    required: true
  branch:
    description: The branch of the schema to check against. Defaults to the name of the PR target branch.
  subgraph:
    description: The name of the subgraph to check. Only required in federated projects.
